### ISSUE TITLE
make setup with mpw-6c showing errors and warnings

### ISSUE THREAD

**Issue by hadirkhan10** [efabless/caravel_user_project#124]
Using `make setup` outputs the following errors and warnings:
```bash
ERROR: tiptop 0.2.2 has requirement rich>=11.0.0, but you'll have rich 10.16.2 which is incompatible.
ERROR: textual 0.1.15 has requirement rich<12.0.0,>=11.0.0, but you'll have rich 10.16.2 which is incompatible.
Installing collected packages: pyyaml, charset-normalizer, requests, click, rich, click-default-group, volare
WARNING: The script normalizer is installed in '/home/mkhan33/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use--no-warn-script-location.  
WARNING: The script volare is installed in '/home/mkhan33/.local/bin' which is not on PATH. 
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed charset-normalizer-2.0.12 click-8.1.3 click-default-group-1.2.2 pyyaml-5.4.1 requests-2.27.1 rich-10.16.2 volare-0.1.3
make[1]: volare: Command not found
```
I had to manually append the /home/mkhan33/.local/bin to $PATH for the `volare` to command to work.

**Comment by ted-xie** [comment]
Hey there! I just had the same issue as you and I think this definitely needs to be fixed. Copying `volare` into a directory on $PATH does technically work but is definitely non-optimal, since it possibly requires root permissions (if copying to `/usr/bin` for example), and is in general kind of clunky. I opted to first setup a python virtual environment and *then* run the setup flow, like so:

```
mkdir -p $HOME/caravel_venv
python3 -m venv $HOME/caravel_venv
source $HOME/caravel_venv/bin/activate
make setup
```

The nice thing about doing setup this way is that the hackiness is reduced somewhat compared to copying binaries around to different places, all modifications to $PATH are automatic, and it follows python best practices through uses of userland virtual environments. No root permissions required, no modifying system-level libraries. I would say it's relatively clean. Ideally `make setup` should do this natively.
