### ISSUE TITLE
make setup fails with latest commit

### ISSUE THREAD

**Issue by vijayank88** [efabless/caravel_user_project#285]
Cloned latest commit and ran `make setup` and fails with following error.
```
make: pip: Command not found
make: *** [Makefile:322: setup-cocotb] Error 127
```

**Comment by M0stafaRady** [comment]
That's because you don't have pip installed in your system. 
You can install it using `sudo apt-get install python3-pip` and rerun `make setup`

This is used to install the cocotb dependencies if you are not planning on using cocotb you can skip by removing `setup-cocotb` 
from the following line then rerun. 
[`setup: check_dependencies install check-env install_mcw openlane pdk-with-volare setup-timing-scripts setup-cocotb`](https://github.com/efabless/caravel_user_project/blob/main/Makefile#L110)

**Comment by vijayank88** [comment]
With `python3` default will be `pip3` got installed.
Update to `@pip3 install caravel-cocotb==1.0.0` got resolved and able to complete `make setup`

**Comment by adrienluitot** [comment]
On MacOs I personnally fixed the error by linking pip3 to pip with macports:
`sudo port select --set pip pip311`                                 
`sudo port select --set pip3 pip311`

Just making an alias in my terminal didn't fix the problem.
